'use client'

import ExperimentVisual from './ExperimentVisual'
import TextLog from './TextLog'

export default function AttentionResponseLab() {
  return (
    <div className="lab-border rounded-lg p-6 bg-lab-surface">
      <div className="mb-6">
        <h2 className="text-xl font-mono text-lab-accent mb-2">
          Attention Response Lab
        </h2>
        <p className="text-sm text-lab-text/70">
          AI model attempts to recognize stimuli or patterns generated by another model.
          Goal: to demonstrate the "noticed/missed" process.
        </p>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <ExperimentVisual />
        </div>
        <div className="lg:col-span-1">
          <TextLog />
        </div>
      </div>
    </div>
  )
}

